// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var AsyncStorage$Rebolt = require("rebolt/src/asyncStorage.js");
var Home$MyReasonReactNativeApp = require("./Home.js");
var NavigationConfig$MyReasonReactNativeApp = require("./NavigationConfig.js");

var component = ReasonReact.statelessComponent("Main");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Curry._5(NavigationConfig$MyReasonReactNativeApp.StackNavigator[/* make */1], /* array */[/* Home */0], /* Some */[(function (state) {
                                  AsyncStorage$Rebolt.setItem("$state", JSON.stringify(Curry._1(NavigationConfig$MyReasonReactNativeApp.StackNavigator[/* Persistence */0][/* encode */0], state)), /* None */0, /* () */0);
                                  return /* () */0;
                                })], /* None */0, /* None */0, (function (_, navigation) {
                                return ReasonReact.element(/* None */0, /* None */0, Home$MyReasonReactNativeApp.make(navigation, /* array */[]));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var Main = /* module */[
  /* component */component,
  /* make */make
];

function app() {
  return ReasonReact.element(/* None */0, /* None */0, make(/* array */[]));
}

exports.Main = Main;
exports.app = app;
/* component Not a pure module */
