// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReRoute$RerouteNative = require("reroute-native/src/ReRoute.js");

var Config = /* module */[];

var include = ReRoute$RerouteNative.CreateNavigation(Config);

var StackNavigator = include[0];

var TabNavigator = include[1];

exports.Config = Config;
exports.StackNavigator = StackNavigator;
exports.TabNavigator = TabNavigator;
/* include Not a pure module */
